メッセージ取得・表示機能の実装
soleil-colza/JetMessenger pull request #10
Opened 2024-02-07 21:15 UTC by soleil-colza

◎ 実装目標
-
- チャンネルからメッセージを取得し、MessageCardとしてLaztColumn内に表示する

◎ 備考
-
- curl -H "authorization: Bot {token} {BASE_URL} /v10/channels/{channelId}/messages?limit={任意の数}"で、Curlでのメッセージ取得には成功しましたがApp上ではまだ思うように動きません。

2024-02-08 01:21 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatViewModel.kt
> +    val messages: LiveData<List<Message>> = _messages
Flow使っちゃったほうが楽かも

2024-02-08 01:21 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatViewModel.kt
> +    val messages: LiveData<List<Message>> = _messages
textStateと同じように書いていけばいける

2024-02-08 01:21 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/data/api/GetMessagesApi.kt
> +    .baseUrl("https://example.com")
> .baseUrl(BuildConfig.BASE_URL)

これで良さそう

2024-02-08 01:21 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> -                )
Scaffoldは消さなくても良さそう

2024-02-08 01:21 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/data/repository/GetMessagesRepository.kt
> +    suspend fun getMessages(): List<Message>
osのMessageは多分狙ってるのと違うクラスになりそう
自分で定義したほうがいいと思われる

2024-02-08 03:21 UTC, clown6613 reviewed
一点だけ確認お願いします。

2024-02-08 03:21 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/data/api/GetMessagesApi.kt
> +    @GET("/messages")
指定するURLが不十分そう

2024-02-13 07:12 UTC, Wansuko-cmd requested changes
確認お願いします

2024-02-13 07:12 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +    viewModel: ChatViewModel
viewModelはChatActivityに持っていた方が良さそう

2024-02-13 07:12 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +    val messagesState = viewModel.messages.collectAsState()
ここら辺のコードもChatActivityに持っていった方が良さそう

2024-02-13 07:12 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +                    .padding(top = 20.dp, bottom = 72.dp),
reversedLayout = trueにすることでチャットアプリっぽい挙動になると思う

2024-02-13 07:12 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatViewModel.kt
> +    val messages: StateFlow<Array<ReceivedMessage>> = _messages
textStateとmessagesは合体してUiStateとする形が一般的
```kt
data class ChatUiState(
    val inputText: String = "",
    val messages: List<ReceivedMessage>: String = "",
)
```

2024-02-13 07:12 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +                GetMessagesRepositoryImpl(Dispatchers.IO, api)
SendMessageRepositoryはapiを引数に取らないのにGetMessagesRepositoryではapiを引数に取っている
どちらかに統一した方がいいと思う（個人的にはapiを引数に取る形が好み）

2024-02-13 11:40 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +                colors = TextFieldDefaults.textFieldColors(Color(0xFF2E3A59)), //適用されてない気がする
文字色の返還をするなら、`TextStyle = TextStyle(color = {color})`でできそうです。

2024-02-14 01:33 UTC, Wansuko-cmd reviewed
LGTM

2024-02-14 01:33 UTC, Wansuko-cmd approved these changes

2024-02-14 01:34 UTC, merged