ローディング時のSkelton UIを実装
soleil-colza/JetMessenger pull request #11
Opened 2024-02-14 01:45 UTC by soleil-colza

◎ 実装目標
-
- isLoading = trueのときSkelton UIを表示する

◎ 実装内容
-
- .skelton修飾子の作成
- MessageCardのPlaceholderに.skeltonを適用、isLoading = trueの場合に表示されるようにする
- .skeltonの動作確認のためfetchMessagesで３秒のdelayを追加

◎ 問題
-
- isLoading時に.skeltonが適切に表示されていない

◎ 確認したこと
-
- uiState.isLoadingが正しく設定されているかどうか(MessageのフェッチがLoadingとして扱われているか)
- .skeleton()の定義が適切か
- MessageCardPlaceholderの周囲に別のコンポーネントがないか
-

2024-02-14 01:57 UTC, Wansuko-cmd requested changes
確認お願いします

2024-02-14 01:57 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatViewModel.kt
> +            delay(3000)
これはいらなさそう？

2024-02-14 01:57 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
> +                        }
これだとうまく表示されないと思う
メッセージを取得するまでの時間稼ぎなのにメッセージがないと表示できないようになってる

例えば10個分表示する・・・みたいな感じにしたほうが良さそう

2024-02-15 04:22 UTC, soleil-colza commented
ライブラリを使う形に書き換えて、skeleton修飾子に関係する部分を削除しました。

2024-02-15 04:47 UTC, clown6613 approved these changes
一点軽微なコメント残しましたが、概ねOKです！

2024-02-15 04:47 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
>  fun MessageCard(message: ReceivedMessage) {
他のファイルから参照できないように、そのファイル内でしか使われていない関数や変数はprivateにしておいたほうが安全。MessageCardPlaceholderなども。

2024-02-15 05:23 UTC, Wansuko-cmd approved these changes
基本的に大丈夫そう
時間があれば確認する程度でOK

2024-02-15 05:23 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/data/DummyMessage.kt
> +)
消しても良さそう？

2024-02-15 05:23 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/data/ChatUiState.kt
>      val messages: Array<ReceivedMessage> = emptyArray(),
ArrayよりはListを使った方が良さそう
ArrayにはtoList()関数があるため、Repositoryなどで置換してしまってもいいかもしれない

2024-02-15 05:23 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/presentation/ChatActivity.kt
>                          .align(Alignment.BottomStart),
画面を横にしたときに横に伸びるようにfillMaxWidth等を設定しても良さそう？

2024-02-15 05:51 UTC, merged