importとUIに関係する軽微な修正
soleil-colza/JetMessenger pull request #2
Opened 2024-01-17 12:39 UTC by soleil-colza

## 実施タスク
前回頂いたコードレビューの反映

## 実施内容

- Retrofitに関係する重複したimportの削除

- ScaffoldへのinnerPaddingの適用

- Columnの削除

## レビューしてほしいこと
上記3点に関して、頂いたコメントに即した変更が出来ているか

## これから取り組むこと
- WebhookのURLを.envに格納する
- Gitの履歴からWebhookのURLを削除する

## 備考

2024-01-17 13:21 UTC, clown6613 approved these changes
Columnの削除を確認できました🙆‍♂️

2024-01-17 13:52 UTC, Wansuko-cmd requested changes
確認お願いします

2024-01-17 13:52 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ApiClient.kt
> +private const val WEBHOOK_URL = "https://discord.com/api/webhooks/1194601189988389007/RXOsVO_r7FfUoQf8KTRTRIol7SVx1zWWrvN9eT6vcdgLQYJoxmZ88PjW00jnhLpUh9Qk"
マージ前に履歴から削除してくれると助かる

2024-01-17 13:52 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +                    }
ここ、ViewModel使う予定だと思うしViewModelに移動しても良さそう
coroutineScopeを作って管理する必要がなくなるのでおすすめ

```kt
class MainViewModel : ViewModel() {
    fun sendMessage() {
        viewModelScope.launch(Dispatchers.IO) { // viewModelScopeというAndroid側が管理してるcoroutineScopeがある
            client.sendMessage(DiscordMessage(textState.value))
        }
    }
}
```

雰囲気こんな感じでViewModelを書いておいて、MainActivityから呼び出す

```kt
val viewModel = viewModels()

// ...
FloatingActionButton(onClick = viewModel::sendMessage)
```

2024-01-17 13:52 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
>      ) {
ScaffoldのpaddingValueを外側の要素に適用した方がいい

https://blog.keithyokoma.dev/entry/2022/08/30/193024

2024-01-18 00:57 UTC, Wansuko-cmd commented
レビューして欲しいこと見落としてました、すみません

1. [「ScaffoldへのinnerPaddingの適用」ができてない](https://github.com/soleil-colza/JetMessenger/pull/2#discussion_r1455613025)のでそちらの修正お願いします
2. https://github.com/soleil-colza/JetMessenger/pull/2#discussion_r1455594707 についてに修正する点、確認しました
3. [こちらも](https://github.com/soleil-colza/JetMessenger/pull/2#discussion_r1455608028)将来的にでいいので適用してもらえると良さそうです

2024-01-23 15:59 UTC, closed without merging