Interfaceの統合と環境変数のgitignore
soleil-colza/JetMessenger pull request #5
Opened 2024-01-23 15:57 UTC by soleil-colza

◎ 実装内容
-
- MainApplication.kt, JetMessengerApp.ktの削除
- DiscordWebhookとWebhookApiの統合
- WEBHOOK_URL定義を含むgradle.propertiesのgitignoreとGitからの削除

◎ レビューしてほしいこと
-
- 上記内容が適切に実装出来ているか

◎ これから取り組むこと
-
- paddingValueの適用

◎ 備考
-
- MainViewModelの記述に誤りがある気がするので、明日確認します

2024-01-23 18:19 UTC, clown6613 commented on .gitignore
> +gradle.properties
appモジュール配下のgradle.propertiesを指定すると良いです。
この前画面共有したときにやったように、AndroidStudioの左上から"Android" -> "Project"でみると階層をつかみやすいです。

2024-01-23 18:39 UTC, clown6613 requested changes
- MainApplication.kt, JetMessengerApp.ktの削除
- DiscordWebhookとWebhookApiの統合
2点の完了を確認しました。
以下のレビューに対応していただければOKです。
textStateがviewModelと連動していないように見えるので、今あるレビューに対応後で良いので直していきましょう。

2024-01-23 18:39 UTC, clown6613 commented on .gitignore
> +gradle.properties
appモジュール配下のgradle.propertiesを指定すると良いです。
この前画面共有したときにやったように、AndroidStudioの左上から"Android" -> "Project"でみると階層をつかみやすいです。

2024-01-23 18:39 UTC, clown6613 commented on app/build.gradle.kts
> +        sourceCompatibility = JavaVersion.VERSION_17
予期せぬエラーを防ぐために、この辺も戻しておいて良いかも。
この箇所の変更理由は、Hilt使ってた時にエラーが出て、一時的にjavaのコード書いてたからですかね？

2024-01-23 18:39 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +                    UserInputScreen(MainViewModel())
定義したviewModelを使おう！

2024-01-24 00:32 UTC, soleil-colza commented
お忙しい中レビューありがとうございます！🙇🏻‍♀️

2024-01-24 02:26 UTC, Wansuko-cmd requested changes
一度この部分の修正をお願いしたいです

2024-01-24 02:26 UTC, Wansuko-cmd commented on gradle.properties
> -android.nonTransitiveRClass=true
このファイルはGradleやAndroidの設定が入ってるから消さない方がよさそう
https://docs.gradle.org/current/userguide/build_environment.html

2024-01-24 02:26 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +            if (rawText != null && rawText.isEmpty()) {
これだと、rawTextが空文字の時にのみ実行されてしまう
例えば`!rawText.isNullOrEmpty()`とかだと文字列が入った時のみになりそう

2024-01-24 02:26 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +
こんな感じに書くとよりスッキリしたコードになりそう

今の実装っぽく
```kt
val message = textState.value ?: return@launch
if (message.isNotBlank()) DiscordWebhook.sendMessage(DiscordMessage(message))
```

関数型っぽく
```kt
textState.value
    ?.let { text -> DiscordMessage(text) }
    ?.also { message -> DiscordWebhook.sendMessage(message) }
```

2024-01-24 02:26 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +    val scope = rememberCoroutineScope()
このscopeは使わなさそう

2024-01-24 02:26 UTC, Wansuko-cmd commented on app/gradle.properties
> +WEBHOOK_URL="https://discord.com/api/webhooks/1194601189988389007/RXOsVO_r7FfUoQf8KTRTRIol7SVx1zWWrvN9eT6vcdgLQYJoxmZ88PjW00jnhLpUh9Qk/"
これをGitの履歴から消して欲しい

2024-01-24 06:48 UTC, soleil-colza commented on .gitignore
> +gradle.properties
app/gradle.propertiesをgitignoreし、バージョン管理上の履歴も削除しました。
また、gradle.propertiesに重複して記載していたWEBHOOK_URLの定義も削除しました！

2024-01-24 06:53 UTC, soleil-colza commented on app/build.gradle.kts
> +        sourceCompatibility = JavaVersion.VERSION_17
おっしゃる通りです！戻しました🙆🏻‍♀️

2024-01-24 06:54 UTC, soleil-colza commented on gradle.properties
> -android.nonTransitiveRClass=true
復元しました！ありがとうございます🙇🏻‍♀️

2024-01-24 06:56 UTC, soleil-colza commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +    val scope = rememberCoroutineScope()
削除しました！ありがとうございます。

2024-01-24 07:50 UTC, soleil-colza commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +
後者で書き直してみました！条件が明確になり、可読性が上がって嬉しいです。２通りもご提案いただきありがとうございます！

2024-01-24 09:29 UTC, Wansuko-cmd requested changes
このようなコマンドでフォーマットがかかるため、コードを綺麗にしていってもよさそう

<img width="800" alt="スクリーンショット 2024-01-24 12 38 47" src="https://github.com/soleil-colza/JetMessenger/assets/63241922/bf96a71a-0504-4f4a-a18d-9118b1ea2fe6">

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +            }
この上の部分はいらなさそう

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +                    UserInputScreen(MainViewModel())
多分この部分直ってない

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    val textState = MutableLiveData<String>()
ViewModelに定義してるのはいいけど今のところ使ってない気がする
UIの状態を反映させるためにTextのonValueChangeで反映させた方がよさそう

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    val textState = MutableLiveData<String>()
こちらはどちらでもいいけど、最近はFlow（厳密にはMutableStateFlow）を使ってるパターンの方が多いと思う

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    private val viewModelScope = CoroutineScope(Dispatchers.Main)
これはいらなそう(ViewModelにviewModelScopeがあるため、それをimportして使う方がいい)

2024-01-24 09:29 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    val DiscordWebhook = retrofit.create(DiscordWebhook::class.java)
命名規則的には最初の文字は小文字の方がいい

2024-01-24 10:34 UTC, soleil-colza commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    val DiscordWebhook = retrofit.create(DiscordWebhook::class.java)
適用しました！ありがとうございます。

2024-01-24 11:24 UTC, clown6613 approved these changes
命名規則についての軽いレビューをしてあります。
あとは、MainActivityのviewModel部分を直していただければと🙆‍♂️

2024-01-24 11:24 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/ApiClient.kt
> +data class discordMessage(
interfaceとdataclassの命名はPascalCaseが良いです
[Doc](https://kotlinlang.org/docs/coding-conventions.html#naming-rules)

2024-01-25 02:49 UTC, Wansuko-cmd requested changes
一部直ってなさそうな部分があるのでこちらの確認をお願いします

2024-01-25 02:49 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +            }
この部分直ってなさそう？

2024-01-25 08:20 UTC, Wansuko-cmd requested changes
確認お願いします

2024-01-25 08:20 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
> +    val textState = remember { viewModel.textState }
多分この部分はこのままじゃ動かない？
後々のPull Requestの中で修正していく形をとりたい

2024-01-25 08:20 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +            }
残ってる上の部分もいらなそう

2024-01-25 08:20 UTC, Wansuko-cmd commented on app/build.gradle.kts
> +android.buildFeatures.buildConfig = true
これ51行目に書いてるからいらなさそう？

2024-01-25 08:20 UTC, Wansuko-cmd commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
>  @SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
これいらなさそう

2024-01-25 16:31 UTC, soleil-colza commented on app/src/main/java/com/example/jetmessenger/MainActivity.kt
>  @SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
削除しました！ありがとうございます。

2024-01-25 16:32 UTC, soleil-colza commented on app/build.gradle.kts
> +android.buildFeatures.buildConfig = true
削除しました！ありがとうございます！

2024-01-26 01:38 UTC, clown6613 approved these changes
些細なコメントを残しました。
こちらに対応してもらえば、自分からのレビューは以上になると思うのでマージOKです。

2024-01-26 01:38 UTC, clown6613 commented on app/build.gradle.kts
> +android.buildFeatures.buildConfig = true
削除漏れ？

2024-01-26 01:38 UTC, clown6613 commented on app/src/main/java/com/example/jetmessenger/ViewModel.kt
> +    val DiscordWebhook = retrofit.create(DiscordWebhook::class.java)
適用漏れ？

2024-01-26 04:43 UTC, soleil-colza commented on app/build.gradle.kts
> +android.buildFeatures.buildConfig = true
こちらの差分がPushに乗っていませんでした💦すみません

2024-01-26 05:15 UTC, Wansuko-cmd approved these changes
LGTM

2024-01-26 05:17 UTC, merged